Add compression and better error handling
containous/oxy pull request #50
Opened 2018-01-08 21:16 UTC by Juliens

- add compression if client send the compression header and backend valid compression
- handle close message correctly and log only real error

2018-01-09 09:25 UTC, ldez requested changes

2018-01-09 09:25 UTC, ldez commented on forward/fwd.go
> +	errbackend := make(chan error)
/errbackend/errBackend/
/errclient/errClient/

2018-01-09 09:25 UTC, ldez commented on forward/fwd_websocket_test.go
> +
could you remove this line and add some before ?

2018-01-09 09:25 UTC, ldez commented on forward/fwd_websocket_test.go
> +
could you remove this line and add some before ?

2018-01-09 15:39 UTC, ldez approved these changes
LGTM

2018-01-09 18:20 UTC, ldez requested changes

2018-01-09 18:20 UTC, ldez commented on forward/fwd.go
> +	}
```go
dialer.EnableCompression = strings.Contains(req.Header.Get("Sec-Websocket-Extensions"), "permessage-deflate")
```

2018-01-09 18:20 UTC, ldez commented on forward/fwd.go
> +	}
```go
upgrader.EnableCompression = strings.Contains(resp.Header.Get("Sec-Websocket-Extensions"), "permessage-deflate")
```

2018-01-11 14:41 UTC, ldez approved these changes
LGTM

2018-01-11 14:45 UTC, mmatur approved these changes
LGTM

2018-01-11 15:41 UTC, nmengin approved these changes

2018-01-11 15:45 UTC, merged